### ISSUE TITLE
后端启动失败

### ISSUE THREAD

**Issue by ysun** [huge-dream/django-vue3-admin#20]
pip3 install -r requirements.txt
python version: Python 3.10.12

```
Collecting mysqlclient==2.2.0
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/de/9c/b176826e8994551ce826404dab97e305a4bb76c8b0a4e016fabda2901c71/mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 154, in <module>
          ext_options = get_config_posix(get_options())
        File "setup.py", line 48, in get_config_posix
          pkg_name = find_package_name()
        File "setup.py", line 27, in find_package_name
          raise Exception(
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by pydevcasts** [comment]
The error "mysqlclientpypy install" usually indicates that you are trying to install the mysqlclient library for Python but are missing necessary dependencies.

To install mysqlclient on Debian/Ubuntu systems, use the following command:

sudo apt-get install python3-dev default-libmysqlclient-dev build-essential pkg-config   
For other distributions like CentOS/RedHat, use:

sudo yum install python3-devel mysql-devel  
Then, use pip to install mysqlclient:

pip3 install mysqlclient  
Double-check the specific dependencies needed for your system and Python version.

another way you can delete mysqliclient in requirements.txt and put the mysqlclient==2.2.4

**Comment by zhti** [comment]
安装mysqlclient失败，以下是centos7的安装方法
1、检查mariadb
rpm -qa | grep mariadb
如果有rpm包则删除
rpm -e mariadb-devel-5.5.68-1.el7.x86_64
rpm -e mariadb-libs-5.5.68-1.el7.x86_64 --nodeps
2、检查mysql
rpm -aq | grep mysql
如果没有rpm从官网下载https://dev.mysql.com/downloads/mysql/，安装以下rpm，必须顺序执行
rpm -ivh mysql-community-common-8.0.39-1.el7.x86_64.rpm
rpm -ivh mysql-community-libs-8.0.39-1.el7.x86_64.rpm
rpm -ivh mysql-community-client-plugins-8.0.39-1.el7.x86_64.rpm
rpm -ivh mysql-community-libs-8.0.39-1.el7.x86_64.rpm
rpm -ivh mysql-community-devel-8.0.39-1.el7.x86_64.rpm

**Comment by ysun** [comment]
> The error "mysqlclientpypy install" usually indicates that you are trying to install the mysqlclient library for Python but are missing necessary dependencies.
> 
> To install mysqlclient on Debian/Ubuntu systems, use the following command:
> 
> sudo apt-get install python3-dev default-libmysqlclient-dev build-essential pkg-config For other distributions like CentOS/RedHat, use:
> 
> sudo yum install python3-devel mysql-devel Then, use pip to install mysqlclient:
> 
> pip3 install mysqlclient Double-check the specific dependencies needed for your system and Python version.
> 
> another way you can delete mysqliclient in requirements.txt and put the mysqlclient==2.2.4

Cool I got it, by installing package with apt. Appreciate it~!
